version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/go/src
    ports:
      - "${APP_PORT:-8080}:8080"
      # - 8080:8080
    depends_on:
      - db
    env_file:
      - ./.env
    command: go run main.go
    networks:
      - db-net
      - api-net
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - db-net
volumes:
  db-store:

networks:
  db-net:  # APIサーバ<=>PostgleSQL間用ネットワーク
  api-net: # クライアント<=>APIサーバ間用ネットワーク